version: "3.8"

services:
  my_app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_IP: DATABASE
      DB_NAME: task_management
      DB_PASSWORD: 1234
    depends_on:
      - DATABASE
  DATABASE:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
